export const INPUT_CHANGE = "INPUT_CHANGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const CLEAR_FORM = "CLEAR_FORM";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";



//comments
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE";
export const ARTICLES_INPUT_CHANGE = "ARTICLES_INPUT_CHANGE";
export const ADD_ARTICLES_SUCCESS = "ADD_ARTICLES_SUCCESS";
export const ADD_ARTICLES_FAILURE = "ADD_ARTICLES_FAILURE";
export const LIKE_ARTICLES_SUCCESS = "LIKE_ARTICLES_SUCCESS";
export const LIKE_ARTICLES_FAILURE = "LIKE_ARTICLES_FAILURE";
export const UNLIKE_ARTICLES_SUCCESS = "UNLIKE_ARTICLES_SUCCESS";
export const UNLIKE_ARTICLES_FAILURE = "UNLIKE_ARTICLES_FAILURE";
export const ADD_ARTICLES_REPLY_SUCCESS =
  "ADD_ARTICLES_REPLY_SUCCESS";
export const ADD_ARTICLES_REPLY_FAILURE =
  "ADD_ARTICLES_REPLY_FAILURE";
export const DELETE_ARTICLES_SUCCESS = "DELETE_ARTICLES_SUCCESS";
export const DELETE_ARTICLES_FAILURE = "DELETE_ARTICLES_FAILURE";
export const UPDATE_ARTICLES_SUCCESS = "UPDATE_ARTICLES_SUCCESS";
export const UPDATE_ARTICLES_FAILURE = "UPDATE_ARTICLES_FAILURE";
export const SUBJECT_INPUT_CHANGE = "SUBJECT_INPUT_CHANGE";
export const REPORT_LESSON_SUCCESS = "REPORT_LESSON_SUCCESS";
export const REPORT_LESSON_FAILURE = "REPORT_LESSON_FAILURE";
export const ADD_NEW_ADMIN_TO_CLASS_SUCCESS = "ADD_NEW_ADMIN_TO_CLASS_SUCCESS";
export const ADD_NEW_ADMIN_TO_CLASS_FAILURE = "ADD_NEW_ADMIN_TO_CLASS_FAILURE";

export const ADD_POST_TO_FEED_SUCCESS = "ADD_POST_TO_FEED_SUCCESS";
export const ADD_POST_TO_FEED_FAILURE = "ADD_POST_TO_FEED_FAILURE";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const COMMENT_TO_POST_SUCCESS = "COMMENT_TO_POST_SUCCESS";
export const COMMENT_TO_POST_FAILURE = "COMMENT_TO_POST_FAILURE";

export const LIKE_A_POST_SUCCESS = "LIKE_A_POST_SUCCESS";
export const LIKE_A_POST_FAILURE = "LIKE_A_POST_FAILURE";

export const UNLIKE_A_POST_SUCCESS = "UNLIKE_A_POST_SUCCESS";
export const UNLIKE_A_POST_FAILURE = "UNLIKE_A_POST_FAILURE";

export const LIKE_A_POST_COMMENT_SUCCESS = "LIKE_A_POST_COMMENT_SUCCESS";
export const LIKE_A_POST_COMMENT_FAILURE = "LIKE_A_POST_COMMENT_FAILURE";

export const UNLIKE_A_POST_COMMENT_SUCCESS = "UNLIKE_A_POST_COMMENT_SUCCESS";
export const UNLIKE_A_POST_COMMENT_FAILURE = "UNLIKE_A_POST_COMMENT_FAILURE";
